server:
  port: 8001
spring:
  application:
    name: helloserver




eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/,http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/
